nelmio_cors:
    defaults:
        origin_regex: true
    paths:
        '^/api/':
            allow_origin: '*'
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Accept', 'Accept-Language', 'Content-Language', 'Content-Type', 'Authorization']
            expose_headers: ['*']
            max_age: 3600